"""Generate src/hw_tables.rs from python-validity's hw_tables.py (GPL-3.0 reference)."""
import ast
import os
import re
import sys

SENSOR_DIR = r"D:\projects\code\omnilock\omnilock-bio\reference\python-validity\validitysensor"
OUT = r"D:\projects\code\omnilock\omnilock-bio\src\hw_tables.rs"

src = open(os.path.join(SENSOR_DIR, "hw_tables.py"), encoding="utf-8").read()
tree = ast.parse(src)


def get_call_values(assign_target):
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == assign_target:
                    assert isinstance(node.value, ast.List), assign_target
                    out = []
                    for elt in node.value.elts:
                        assert isinstance(elt, ast.Call), elt
                        out.append([c.value for c in elt.args])
                    return out
    raise KeyError(assign_target)


dev_info = get_call_values("dev_info_table")
flash_ic = get_call_values("flash_ic_table")

lines = []
lines.append("// GENERATED by scripts/gen_hw_tables.py from python-validity's hw_tables.py")
lines.append("// (GPL-3.0 reference, SimpleX-T fork, branch feat/sensor-type-0xd51).")
lines.append("// Do not edit by hand; regenerate instead.")
lines.append("")
lines.append("pub struct DeviceInfo {")
lines.append("    pub major: u16,")
lines.append("    pub dev_type: u16,")
lines.append("    pub version: u8,")
lines.append("    pub version_mask: u8,")
lines.append("    pub name: &'static str,")
lines.append("}")
lines.append("")
lines.append("pub const DEV_INFO_TABLE: &[DeviceInfo] = &[")
for major, dev_type, version, vmask, name in dev_info:
    line = (
        "    DeviceInfo { major: 0x%04x, dev_type: 0x%04x, version: 0x%02x, version_mask: 0x%02x, name: %r },"
        % (major, dev_type, version, vmask, name)
    )
    lines.append(line.replace("'", '"'))
lines.append("];")
lines.append("")
lines.append("pub struct FlashIcInfo {")
lines.append("    pub name: &'static str,")
lines.append("    pub size: u32,")
lines.append("    pub f18: u8,")
lines.append("    pub jid0: u8,")
lines.append("    pub jid1: u8,")
lines.append("    pub f1b: u8,")
lines.append("    pub f1c: u32,")
lines.append("    pub f1e: u8,")
lines.append("    pub sector_size: u32,")
lines.append("    pub sector_erase_cmd: u8,")
lines.append("    pub f25: u8,")
lines.append("    pub f26: u8,")
lines.append("}")
lines.append("")
lines.append("pub const FLASH_IC_TABLE: &[FlashIcInfo] = &[")
for name, size, f18, jid0, jid1, f1b, f1c, f1e, ss, sec, f25, f26 in flash_ic:
    line = (
        "    FlashIcInfo { name: %r, size: %d, f18: 0x%02x, jid0: 0x%02x, jid1: 0x%02x, f1b: 0x%02x, f1c: 0x%x, f1e: 0x%02x, sector_size: 0x%x, sector_erase_cmd: 0x%02x, f25: 0x%02x, f26: 0x%02x },"
        % (name, size, f18, jid0, jid1, f1b, f1c, f1e, ss, sec, f25, f26)
    )
    lines.append(line.replace("'", '"'))
lines.append("];")
lines.append("")
lines.append("pub fn dev_info_lookup(major: u16, ver: u16) -> Option<DeviceInfo> {")
lines.append("    let mut fuzzy_match: Option<&DeviceInfo> = None;")
lines.append("")
lines.append("    for i in DEV_INFO_TABLE {")
lines.append("        if i.major != major {")
lines.append("            continue;")
lines.append("        }")
lines.append("        let masked_ver = i.version & i.version_mask;")
lines.append("        if ver == 0 || masked_ver == 0 {")
lines.append("            fuzzy_match = Some(i);")
lines.append("        } else if ver == masked_ver {")
lines.append("            return Some(DeviceInfo {")
lines.append("                major: i.major,")
lines.append("                dev_type: i.dev_type,")
lines.append("                version: i.version,")
lines.append("                version_mask: i.version_mask,")
lines.append("                name: i.name,")
lines.append("            });")
lines.append("        }")
lines.append("    }")
lines.append("")
lines.append("    match fuzzy_match {")
lines.append("        Some(f) => Some(DeviceInfo {")
lines.append("            major: f.major,")
lines.append("            dev_type: f.dev_type,")
lines.append("            version: f.version,")
lines.append("            version_mask: f.version_mask,")
lines.append("            name: f.name,")
lines.append("        }),")
lines.append("        None => None,")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("pub fn flash_ic_table_lookup(")
lines.append("    jedec_id0: u16, jedec_id1: u16, size: u32,")
lines.append(") -> Option<&'static FlashIcInfo> {")
lines.append("    FLASH_IC_TABLE")
lines.append("        .iter()")
lines.append("        .find(|ic| ic.jid0 as u16 == jedec_id0 && ic.jid1 as u16 == jedec_id1 && ic.size == size)")
lines.append("}")
lines.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(lines))
print("wrote %s (%d device rows, %d flash rows)" % (OUT, len(dev_info), len(flash_ic)))